apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fullstack-app
  labels:
    app: bookmark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack-app
  template:
    metadata:
      labels:
        app: fullstack-app
    spec:
      containers:
      - name: bookmark-app
        image: bookmark-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3838
        envFrom:
        - configMapRef:
            name: bookmark-app-config-map
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name